### ISSUE TITLE
Les dons n'ont pas d'effet sur la fiche de personnage

### ISSUE THREAD

**Issue by Marthin-** [SvenWerlen/foundryvtt-pathfinder1-fr#1]
Bonjour, et déjà merci beaucoup pour ce compendium :)

Visiblement les dons n'ont pas d'effet pour l'instant. Par exemple en important Science de l'Initiative sur un PJ son initiative ne récupère pas de +4

Est-ce que c'est une feature / pas encore implémenté / un bug ?

Merci d'avance :)

**Comment by Marthin-** [comment]
(Avec un screenshot au cas où)
![2020-05-18-112743_1050x560_scrot](https://user-images.githubusercontent.com/10075220/82197024-bee2c500-98fa-11ea-9251-1e9f5b8d7e8a.png)

**Comment by SvenWerlen** [comment]
Bonjour Marthin,

Merci

Oui, en effet, ce n'est pas une feature dans le compendium. Les dons sont importés à partir des données sur www.pathfinder-fr.org mais c'est impossible pour moi d'ajouter les "Effets" pour chaque don. C'est un travail fastidieux que je n'ai pas prévu faire. Par contre, tu peux éditer le don sur le personnage et ajouter l'effet manuellement.

**Comment by deurk** [comment]
Je pense que pour que les compendium soient vraiment utiles, c'est en effet quelque chose qui doit être fait. Est-ce que la vocation de ton dépôt est de récupérer les contributions des gens qui feraient cet effort ?

**Comment by SvenWerlen** [comment]
Je ne recommande pas modifier les compendiums car ils sont générés automatiquement. Par contre, je peux créer des fichiers séparés pour les "buffs" dans lesquels des personnes pourraient contribuer et qui seraient alors fusionnés dans les compendiums. Je propose d'ouvrir cette discussion sur Discord pour trouver le meilleur moyen et les contributeurs pour travailler là-dessus.

**Comment by deurk** [comment]
OK pour moi: deurk#5568 :)

**Comment by SvenWerlen** [comment]
Parfait, j'ai lancé la discussion sur le canal #pf1 du Discord de Pathfinder "La Fonderie"

**Comment by deurk** [comment]
Je le trouve comment ce Discord ? :)

**Comment by SvenWerlen** [comment]
Je pensais que c'était connu: voilà [https://discord.gg/pPSDNJk](https://discord.gg/pPSDNJk)

**Comment by deurk** [comment]
C'est donc un travail "en cours" mais qui risque de prendre du temps, ceci dit tout le monde peut maintenant contribuer via Data-Toolbox (https://github.com/SvenWerlen/fvtt-data-toolbox) :) @Marthin-

**Comment by deurk** [comment]
Je pense qu'on peut fermer ce ticket, il "n'y a qu'a" utiliser ce que tu as créé pour ajouter les effets aux dons du compendium...
