### ISSUE TITLE
plusieurs petit soucis sur pf1 foundry

### ISSUE THREAD

**Issue by sven-ati** [SvenWerlen/foundryvtt-pathfinder1-fr#10]
Bonjour Dorgendubal, je ne doute pas que tu dois faire plusieurs choses en même temps du coup je pense que le mieux est de te signaler les soucis rencontré sur pf1 foundry ici: 

j'ai vue quelque personnes sur le discord qui n'arrive plus à importé le bestiaire via ta macro: 
voici l'erreur rencontré:
![image](https://user-images.githubusercontent.com/40357960/135609372-cdae5ccd-1280-43d8-943c-58fb743cd9e1.png)
ensuite de mon côté, j'ai des erreurs suite au ajoute d'effet sur mes token, à première vue ça viendrai des effets du compendium effet: 
quand j'en ajoute, exemple avec rage, j'ai une erreur et l'icône ne quitte plus mon token ... j'ai tester avec d'autre icônes et j'ai également cette erreur. je n'en ai pas avec les faits main, par contre j'obtiens une alerte mais a partir du moment ou j'ai ajouté un effet du compendium j'ai l'erreur je te joint différentes images : 
Icônes: 
![image](https://user-images.githubusercontent.com/40357960/135609749-95b654ce-a622-4a82-a7e7-f4a603e0f3bc.png)
erreurs:
![image](https://user-images.githubusercontent.com/40357960/135609785-461fc6e9-0dbf-4ef1-aeaf-709c74d1d134.png)
alertes: 
![image](https://user-images.githubusercontent.com/40357960/135609807-c63ac75e-4fd1-45ab-b14e-53d8085a4e4d.png)

J'ai l'impression que pf1 n'est plus soutenu/géré, j'espère me tromper :) 

d'avance merci! 
Bonne journée, soirée ou autres en fonction de l'heure chez toi :p 

Sven (Zword - Sven sur le discord)

**Comment by SvenWerlen** [comment]
Merci de me rapporter ce  problème. Je suis effectivement plutôt occupé mais je vais essayer de regarder le tout cette semaine.

**Comment by SvenWerlen** [comment]
La version `v-1.24.3` devrait corriger les deux problèmes
