### ISSUE TITLE
Liens web affichés incorrectement

### ISSUE THREAD

**Issue by deurk** [SvenWerlen/foundryvtt-pathfinder1-fr#2]
Peut-être est-ce lié à un changement du core FVTT ou du module PF1 mais tous les liens du compendium s'affichent maintenant de manière incorrecte.

![2020-06-27 14_23_02-Foundry Virtual Tabletop • A Standalone Virtual Tabletop Application](https://user-images.githubusercontent.com/498032/85922213-e2961500-b881-11ea-8e00-440dc30f1d86.png)

**Comment by SvenWerlen** [comment]
En effet, une mise à jour de Foundry ou du système Pf1 semble gérer désormais les liens différemment. Je vais regénérer les compendiums pour corriger le tout.

**Comment by deurk** [comment]
Je viens de voir que c'est un bug de Foundry qui a déjà un hotfix... donc attendons plutôt la prochaine version

**Comment by SvenWerlen** [comment]
Oh, je viens de voir également. [Discord](https://discordapp.com/channels/170995199584108546/725021759144984646/725432178774769695). 
J'ai testé le fix et ça résoud le problème. C'est donc bien un bogue dans FoundryVTT
