### ISSUE TITLE
[COMPENDIA] Description des rations de survie incorrecte

### ISSUE THREAD

**Issue by deurk** [SvenWerlen/foundryvtt-pathfinder1-fr#3]
Il semblerait que toutes les rations aient recues la description du rat.
https://www.pathfinder-fr.org/Wiki/Pathfinder-RPG.Nourriture%20et%20Boissons.ashx#Rations%20de%20survie

https://media.discordapp.net/attachments/715985906439553140/732007361228570664/unknown.png
(remonté par Chibi Zaké)

**Comment by SvenWerlen** [comment]
Corrigé dans 1.3.5
![image](https://user-images.githubusercontent.com/938060/87265227-42024080-c490-11ea-949f-ee9ac3b7eda0.png)
