### ISSUE TITLE
Distances des sorts ne sont pas traduites

### ISSUE THREAD

**Issue by Almarane** [SvenWerlen/foundryvtt-pathfinder1-fr#7]
Lorsqu'on va sur l'onglet Sorts d'une fiche de personnage, les portées des sorts sont indiquées en pieds. C'est également le cas dans les descriptions des sorts.

**Comment by SvenWerlen** [comment]
Oui, c'est une amélioration à soumettre au système `pf1` plutôt qu'au module `pf1-fr` mais je vais le garder et si j'ai le temps, soumettre un changement à l'auteur du système. Merci d'avoir rapporté le problème.

**Comment by SvenWerlen** [comment]
Les changements étaient relativement simple à faire. J'ai soumis une contribution au système. Lorsqu'ils seront acceptés, le système supportera les unités de mesure "m" pour les portées de sort.

https://gitlab.com/Furyspark/foundryvtt-pathfinder1/-/merge_requests/91

**Comment by SvenWerlen** [comment]
La _merge request_ contient des captures d'écran qui présentent à quoi ça ressemblera.
