### ISSUE TITLE
ajustements des pnj du bestiaire 

### ISSUE THREAD

**Issue by sven-ati** [SvenWerlen/foundryvtt-pathfinder1-fr#8]
Nous n'avons plus accès à la modification "d'ajustements" et donc on ne peut plus cacher l'icone petit détail mais voilà je te le signale comme demandé sur le discord :) 

Bonne journée! et encore merci pour tout ton travail!

**Comment by SvenWerlen** [comment]
Corrigé dans la version `v-1.6.0`. J'en ai profité pour changer le comportement par défaut. L'icône est désormais masquée par défaut pour toutes les créatures du bestiaire.
