### ISSUE TITLE
Ajout d'un compendium d'attaques naturelles

### ISSUE THREAD

**Issue by Almarane** [SvenWerlen/foundryvtt-pathfinder1-fr#9]
Voir le fichier suivant :
[attaques-naturelles.txt](https://github.com/SvenWerlen/foundryvtt-pathfinder1-fr/files/6018210/attaques-naturelles.txt)

**Comment by SvenWerlen** [comment]
![image](https://user-images.githubusercontent.com/938060/108638554-da689680-745d-11eb-9a4c-f390fcc9443e.png)

**Comment by SvenWerlen** [comment]
Intégré!
